version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          cd /var/www/html && git pull origin circle

workflows:
  my-custom-workflow:
    jobs:
<<<<<<< HEAD
      - my-job-name
=======
      - my-job-name
>>>>>>> 75b344bc744d638915c309d441ae7b5f4baa5158
