version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install apache2
          sudo a2enmod rewrite
          sudo service apache2 restart
          sudo chown -R ubuntu:ubuntu /var/www/html 
          sudo apt-get install php7.4
          cd /var/www/html && git pull origin circle

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
