version: 2.1

description: An orb with some simple ways to help you with your first build.

commands:
  circleci-env-highlights:
    steps:
    - run:
        command: |-
          cd /var/www/html/ && git pull origin circle
jobs:
  hello-build:
    executor: default
    steps:
    - circleci-env-highlights
