version: 2.1
jobs:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
         fingerprints:
           - "1e:d9:f3:a7:51:35:47:e7:8f:e1:20:eb:a0:9b:cd:6c"
      - checkout
      - run:
         name: Setup
         command: |
           chmod 755 .circleci/deploy.sh
           ssh-keyscan 65.2.153.14 >> ~/.ssh/known_hosts
      - run: |
           git pull origin circle
      - run:
         name: Deploy
         command: ./.circleci/deploy.sh
workflows:
  workflow:
    jobs:
      - my-custom-executor
